name: Test Windows to Linux Publishing

on:
  push:
    branches: [ issue-9-231cfae8 ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.24
      id: cuda-toolkit
      with:
        cuda: '12.4.0'
        sub-packages: '["nvcc", "cudart", "visual_studio_integration"]'
        method: 'network'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Test Windows Build (without vcxproj dependencies)
      run: |
        cd Bruteforce
        dotnet build Bruteforce.csproj -c Release

    - name: Test Linux Publishing from Windows
      run: |
        cd Bruteforce
        dotnet publish Bruteforce.csproj -r linux-x64 -c Release --self-contained

    - name: Check if Linux publish worked
      shell: pwsh
      run: |
        $publishPath = "Bruteforce\bin\Release\net8.0\linux-x64\publish"
        if (Test-Path $publishPath) {
          Write-Host "Success: Linux publish directory created" -ForegroundColor Green
          Get-ChildItem -Path $publishPath | Select-Object Name, Length | Format-Table

          # Check for PTX files
          if (Test-Path "$publishPath\ptx") {
            Write-Host "PTX directory found:" -ForegroundColor Cyan
            Get-ChildItem -Path "$publishPath\ptx" | Select-Object Name, Length | Format-Table
          }

          # Check for libs
          if (Test-Path "$publishPath\libs") {
            Write-Host "Libs directory found:" -ForegroundColor Cyan
            Get-ChildItem -Path "$publishPath\libs" | Select-Object Name, Length | Format-Table
          }
        } else {
          Write-Host "Error: Linux publish directory not found" -ForegroundColor Red
          exit 1
        }

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64-publish
        path: Bruteforce/bin/Release/net8.0/linux-x64/publish/

  verify-linux-artifacts:
    needs: test-windows-build
    runs-on: ubuntu-22.04

    steps:
    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-x64-publish
        path: ./linux-publish

    - name: Verify Linux executable
      run: |
        if [ -f "./linux-publish/Bruteforce" ]; then
          echo "Success: Linux executable found"
          file ./linux-publish/Bruteforce
          chmod +x ./linux-publish/Bruteforce
          echo "Executable permissions set"
        else
          echo "Error: Linux executable not found"
          exit 1
        fi

    - name: Check for CUDA support files
      run: |
        echo "Checking for CUDA support files in publish directory:"
        echo ""

        echo "PTX files:"
        find ./linux-publish -name "*.ptx" 2>/dev/null || echo "No PTX files found"
        echo ""

        echo "Shared libraries:"
        find ./linux-publish -name "*.so" 2>/dev/null || echo "No .so files found"
        echo ""

        echo "DLL files (should not be in Linux build):"
        find ./linux-publish -name "*.dll" 2>/dev/null || echo "No DLL files found (correct)"